name: Deploy to Heroku

on:
  release:
    types: [published]  # Se déclenche uniquement quand tu publies une release

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Verify authorized user
        run: |
          echo "Release triggered by: ${{ github.actor }}"
          if [ "${{ github.actor }}" != "LulDrako" ]; then
            echo "❌ Error: Only LulDrako can deploy!"
            exit 1
          fi
          echo "✅ Authorized - deployment starting"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build Vite assets
        run: npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          buildpack: heroku/php

