name: Tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.2', '8.3']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, curl, libxml, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, tokenizer, fileinfo, ctype, xml
          ini-values: memory_limit=512M
          coverage: none

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install Composer dependencies (no scripts)
        env:
          COMPOSER_NO_INTERACTION: 1
        run: composer install --prefer-dist --no-progress --no-ansi --no-scripts

      - name: Copy environment file
        run: cp .env.example .env

      - name: Use SQLite for tests
        run: |
          sed -i 's/^DB_CONNECTION=.*/DB_CONNECTION=sqlite/' .env || true
          mkdir -p database
          : > database/database.sqlite

      - name: Create storage directories
        run: |
          mkdir -p storage/framework/{sessions,views,cache}
          mkdir -p storage/logs
          mkdir -p storage/app/public
          chmod -R 775 storage bootstrap/cache

      - name: Generate app key & migrate
        run: |
          php artisan key:generate
          php artisan migrate --force --no-interaction || true

      - name: Clear caches (replace post-install)
        run: php artisan optimize:clear

      - name: Execute tests
        run: php artisan test
